local ThisModPath = ModPath 
pcall(function() 
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_dinner/characters/civ_male_butcher_2/civ_male_butcher_2"),
		Idstring("unit"),
		ThisModPath.."xml/446a3c057fb93a30.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_dinner/characters/civ_male_butcher_1/civ_male_butcher_1"),
		Idstring("unit"),
		ThisModPath.."xml/4e8c622d40f15e83.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_fex/characters/civ_female_masquerade_1/civ_female_masquerade_1"),
		Idstring("unit"),
		ThisModPath.."xml/97f2c4f726712f00.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_fex/characters/civ_female_masquerade_2/civ_female_masquerade_2"),
		Idstring("unit"),
		ThisModPath.."xml/be89353d9bbd454d.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_fex/characters/civ_female_masquerade_3/civ_female_masquerade_3"),
		Idstring("unit"),
		ThisModPath.."xml/a9be837997902e59.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_fex/characters/civ_female_masquerade_4/civ_female_masquerade_4"),
		Idstring("unit"),
		ThisModPath.."xml/ac4718b8a0e63643.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_fex/characters/civ_male_masquerade_1/civ_male_masquerade_1"),
		Idstring("unit"),
		ThisModPath.."xml/dbbfe95d40cb216a.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_fex/characters/civ_male_masquerade_2/civ_male_masquerade_2"),
		Idstring("unit"),
		ThisModPath.."xml/474d2d4a92723fc7.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_fex/characters/civ_male_masquerade_3/civ_male_masquerade_3"),
		Idstring("unit"),
		ThisModPath.."xml/a2c2c2a54702d397.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_fex/characters/civ_male_masquerade_4/civ_male_masquerade_4"),
		Idstring("unit"),
		ThisModPath.."xml/f18490b7aa2f6b92.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_nmh/characters/civ_male_doctor_01/civ_male_doctor_01"),
		Idstring("unit"),
		ThisModPath.."xml/002e40a7d6837729.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_nmh/characters/civ_male_doctor_02/civ_male_doctor_02"),
		Idstring("unit"),
		ThisModPath.."xml/a6b325e047f8b579.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_nmh/characters/civ_male_doctor_03/civ_male_doctor_03"),
		Idstring("unit"),
		ThisModPath.."xml/e8712103aa4db8a0.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_nmh/characters/civ_male_scrubs_01/civ_male_scrubs_01"),
		Idstring("unit"),
		ThisModPath.."xml/c20c4ee623562bfb.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_nmh/characters/civ_male_scrubs_02/civ_male_scrubs_02"),
		Idstring("unit"),
		ThisModPath.."xml/2aad9449cb03b87e.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_nmh/characters/civ_male_scrubs_03/civ_male_scrubs_03"),
		Idstring("unit"),
		ThisModPath.."xml/4ddf0a855e8f5a41.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_nmh/characters/civ_male_scrubs_04/civ_male_scrubs_04"),
		Idstring("unit"),
		ThisModPath.."xml/74b0d63e64705224.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_nmh/characters/civ_female_scrubs_01/civ_female_scrubs_01"),
		Idstring("unit"),
		ThisModPath.."xml/5fe1e4f63f92e9ee.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_nmh/characters/civ_female_scrubs_02/civ_female_scrubs_02"),
		Idstring("unit"),
		ThisModPath.."xml/b3ac5cccf655c842.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_nmh/characters/civ_female_scrubs_03/civ_female_scrubs_03"),
		Idstring("unit"),
		ThisModPath.."xml/e56e2fc01b12eeb2.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_nmh/characters/civ_female_scrubs_04/civ_female_scrubs_04"),
		Idstring("unit"),
		ThisModPath.."xml/28e7688714960aba.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_nmh/characters/civ_female_doctor_01/civ_female_doctor_01"),
		Idstring("unit"),
		ThisModPath.."xml/38815917ecde65e9.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_nmh/characters/civ_female_hotpants/civ_female_hotpants"),
		Idstring("unit"),
		ThisModPath.."xml/8dbc1a3e8f91d979.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_chas/characters/civ_male_asian_casual_1/civ_male_asian_casual_1"),
		Idstring("unit"),
		ThisModPath.."xml/2c42b9e12c8f98fb.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_chas/characters/civ_male_asian_casual_2/civ_male_asian_casual_2"),
		Idstring("unit"),
		ThisModPath.."xml/52223c4b21924883.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_chas/characters/civ_male_asian_casual_3/civ_male_asian_casual_3"),
		Idstring("unit"),
		ThisModPath.."xml/cab1542e8f8e16cd.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_chas/characters/civ_female_asian_casual_1/civ_female_asian_casual_1"),
		Idstring("unit"),
		ThisModPath.."xml/237b29a770822e93.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_chas/characters/civ_female_asian_storekeeper/civ_female_asian_storekeeper"),
		Idstring("unit"),
		ThisModPath.."xml/4e57febb14c02362.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_chas/characters/civ_male_auctioneer_2/civ_male_auctioneer_2"),
		Idstring("unit"),
		ThisModPath.."xml/3369ad3fb3c06893.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_glace/characters/npc_prisoner_1/npc_prisoner_1"),
		Idstring("unit"),
		ThisModPath.."xml/0ea0ebcbbb1fe79b.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_glace/characters/npc_prisoner_2/npc_prisoner_2"),
		Idstring("unit"),
		ThisModPath.."xml/2d23fa1b118c035d.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_glace/characters/npc_prisoner_3/npc_prisoner_3"),
		Idstring("unit"),
		ThisModPath.."xml/c6c97c7f157d5b87.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_glace/characters/npc_prisoner_4/npc_prisoner_4"),
		Idstring("unit"),
		ThisModPath.."xml/41f97ebfcabad347.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_glace/characters/npc_prisoner_5/npc_prisoner_5"),
		Idstring("unit"),
		ThisModPath.."xml/fe11c95e5cafca64.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_glace/characters/npc_prisoner_6/npc_prisoner_6"),
		Idstring("unit"),
		ThisModPath.."xml/c823a488a8a218e0.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_glace/characters/npc_yakuza_prisoner/npc_yakuza_prisoner"),
		Idstring("unit"),
		ThisModPath.."xml/05319df4b6ad1952.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_arena/characters/civ_female_fastfood_1/civ_female_fastfood_1"),
		Idstring("unit"),
		ThisModPath.."xml/8f9d6b38748a6e92.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_arena/characters/civ_female_party_alesso_1/civ_female_party_alesso_1"),
		Idstring("unit"),
		ThisModPath.."xml/ee19a202f15db8db.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_arena/characters/civ_female_party_alesso_2/civ_female_party_alesso_2"),
		Idstring("unit"),
		ThisModPath.."xml/e319b92308032dcc.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_arena/characters/civ_male_party_alesso_1/civ_male_party_alesso_1"),
		Idstring("unit"),
		ThisModPath.."xml/88a0480e36cf297f.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_arena/characters/civ_male_party_alesso_2/civ_male_party_alesso_2"),
		Idstring("unit"),
		ThisModPath.."xml/2cbe1df4739fa3de.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_arena/characters/civ_male_alesso_booth/civ_male_alesso_booth"),
		Idstring("unit"),
		ThisModPath.."xml/3d8e386a685b7e3e.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_arena/characters/civ_male_fastfood_1/civ_male_fastfood_1"),
		Idstring("unit"),
		ThisModPath.."xml/2ca880a5b36c8cde.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc1/characters/civ_male_bank_manager_2/civ_male_bank_manager_2"),
		Idstring("unit"),
		ThisModPath.."xml/4ac6f5c7de83ee41.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc1/characters/civ_male_casual_10/civ_male_casual_10"),
		Idstring("unit"),
		ThisModPath.."xml/034cb33a90313033.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc1/characters/civ_male_casual_11/civ_male_casual_11"),
		Idstring("unit"),
		ThisModPath.."xml/48e9b6bbbe79ee9d.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc1/characters/civ_male_firefighter_1/civ_male_firefighter_1"),
		Idstring("unit"),
		ThisModPath.."xml/8b1773dc02ebe194.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc1/characters/civ_male_paramedic_1/civ_male_paramedic_1"),
		Idstring("unit"),
		ThisModPath.."xml/1cbb47fb9e5bde86.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc1/characters/civ_male_paramedic_2/civ_male_paramedic_2"),
		Idstring("unit"),
		ThisModPath.."xml/aef69b52d9f5cf6b.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_mex/characters/civ_male_italian/civ_male_italian"),
		Idstring("unit"),
		ThisModPath.."xml/118bb09ee3f1fdd1.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_des/characters/civ_male_hazmat/civ_male_hazmat"),
		Idstring("unit"),
		ThisModPath.."xml/73cacdf2cbfc2cbc.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_des/characters/civ_male_des_scientist_01/civ_male_des_scientist_01"),
		Idstring("unit"),
		ThisModPath.."xml/a16ef0d217d4a1c0.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_des/characters/civ_male_des_scientist_02/civ_male_des_scientist_02"),
		Idstring("unit"),
		ThisModPath.."xml/e8b11be98741918d.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_dah/characters/npc_male_cfo/npc_male_cfo"),
		Idstring("unit"),
		ThisModPath.."xml/2a50feaaf7cea171.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_dah/characters/npc_male_ralph/npc_male_ralph"),
		Idstring("unit"),
		ThisModPath.."xml/694019d0144aec74.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc2/characters/civ_female_bank_assistant_1/civ_female_bank_assistant_1"),
		Idstring("unit"),
		ThisModPath.."xml/20be7dd025974787.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc2/characters/civ_female_bank_assistant_2/civ_female_bank_assistant_2"),
		Idstring("unit"),
		ThisModPath.."xml/c3287f97f47ba0a0.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_bex/characters/civ_male_it_guy/civ_male_it_guy"),
		Idstring("unit"),
		ThisModPath.."xml/d3e4a7224b974065.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_bex/characters/civ_male_bex_bank_manager/civ_male_bex_bank_manager"),
		Idstring("unit"),
		ThisModPath.."xml/a252b2a9e68a754f.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_bex/characters/civ_male_bex_business/civ_male_bex_business"),
		Idstring("unit"),
		ThisModPath.."xml/90fb291eb7234379.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_bex/characters/civ_male_mariachi_01/civ_male_mariachi_01"),
		Idstring("unit"),
		ThisModPath.."xml/9e7890db8b7be428.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_bex/characters/civ_male_mariachi_02/civ_male_mariachi_02"),
		Idstring("unit"),
		ThisModPath.."xml/9bb15d46f127f557.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_bex/characters/civ_male_mariachi_03/civ_male_mariachi_03"),
		Idstring("unit"),
		ThisModPath.."xml/21365e5c39e8780c.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_bex/characters/civ_male_mariachi_04/civ_male_mariachi_04"),
		Idstring("unit"),
		ThisModPath.."xml/abbcbf90eb70825a.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_deep/characters/civ_male_deep_dockworker_01/civ_male_deep_dockworker_01"),
		Idstring("unit"),
		ThisModPath.."xml/24efbecc81d5d898.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_deep/characters/civ_male_deep_dockworker_02/civ_male_deep_dockworker_02"),
		Idstring("unit"),
		ThisModPath.."xml/89aaa885b427b419.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_deep/characters/civ_male_deep_dockworker_03/civ_male_deep_dockworker_03"),
		Idstring("unit"),
		ThisModPath.."xml/a3073c1553fdc0db.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_corp/characters/civ_female_marketing_lead/civ_female_marketing_lead"),
		Idstring("unit"),
		ThisModPath.."xml/bb17ec1af384edcc.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_corp/characters/civ_male_researcher_lead/civ_male_researcher_lead"),
		Idstring("unit"),
		ThisModPath.."xml/7ca2b83c8ec3bd9e.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_mad/characters/civ_male_scientist_01/civ_male_scientist_01"),
		Idstring("unit"),
		ThisModPath.."xml/3e589c0d0211f44c.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_mad/characters/civ_male_scientist_02/civ_male_scientist_02"),
		Idstring("unit"),
		ThisModPath.."xml/43fa5e8bd22654ce.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_rvd/characters/npc_cop/npc_cop"),
		Idstring("unit"),
		ThisModPath.."xml/f77a4c32bbf09c4d.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_rvd/characters/npc_mr_brown/npc_mr_brown"),
		Idstring("unit"),
		ThisModPath.."xml/db9a1f1f9e2b8775.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_rvd/characters/npc_mr_pink/npc_mr_pink"),
		Idstring("unit"),
		ThisModPath.."xml/2694ba851e9d4490.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_cane/characters/civ_male_helper_1/civ_male_helper_1"),
		Idstring("unit"),
		ThisModPath.."xml/4b02693553a926c3.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_cane/characters/civ_male_helper_2/civ_male_helper_2"),
		Idstring("unit"),
		ThisModPath.."xml/28f247256e821a74.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_cane/characters/civ_male_helper_3/civ_male_helper_3"),
		Idstring("unit"),
		ThisModPath.."xml/23bb5d4857a1a16c.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_cane/characters/civ_male_helper_4/civ_male_helper_4"),
		Idstring("unit"),
		ThisModPath.."xml/871dae12e3cddbd8.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_holly/characters/civ_male_hobo_1/civ_male_hobo_1"),
		Idstring("unit"),
		ThisModPath.."xml/c53175340ed1c306.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_holly/characters/civ_male_hobo_2/civ_male_hobo_2"),
		Idstring("unit"),
		ThisModPath.."xml/2bc92dcf5ce2f1a7.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_holly/characters/civ_male_hobo_3/civ_male_hobo_3"),
		Idstring("unit"),
		ThisModPath.."xml/8d938e3042902bfb.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_holly/characters/civ_male_hobo_4/civ_male_hobo_4"),
		Idstring("unit"),
		ThisModPath.."xml/011868b13c259383.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_pal/characters/civ_male_mitch/civ_male_mitch"),
		Idstring("unit"),
		ThisModPath.."xml/a43ad0756e300dcc.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_sah/characters/civ_male_gala_guest_03/civ_male_gala_guest_03"),
		Idstring("unit"),
		ThisModPath.."xml/1c853d457b8195d6.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_sah/characters/civ_male_gala_guest_04/civ_male_gala_guest_04"),
		Idstring("unit"),
		ThisModPath.."xml/7cb13369e088cfa0.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_sah/characters/civ_male_gala_guest_05/civ_male_gala_guest_05"),
		Idstring("unit"),
		ThisModPath.."xml/9b21a686a0a7825b.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_sah/characters/civ_male_gala_guest_06/civ_male_gala_guest_06"),
		Idstring("unit"),
		ThisModPath.."xml/d1a106f31b0014de.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_sah/characters/civ_male_auctioneer/civ_male_auctioneer"),
		Idstring("unit"),
		ThisModPath.."xml/42069cd11f3be9e7.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_sah/characters/civ_female_gala_guest_04/civ_female_gala_guest_04"),
		Idstring("unit"),
		ThisModPath.."xml/1709cf76946f8507.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_sah/characters/civ_female_gala_guest_05/civ_female_gala_guest_05"),
		Idstring("unit"),
		ThisModPath.."xml/79a2dc06f8f1ee21.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_sah/characters/civ_female_gala_guest_06/civ_female_gala_guest_06"),
		Idstring("unit"),
		ThisModPath.."xml/bb2e0f2f34d5b7eb.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_sah/characters/civ_male_shacklethorn_waiter_01/civ_male_shacklethorn_waiter_01"),
		Idstring("unit"),
		ThisModPath.."xml/f9f4dc24bd902a55.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_sah/characters/civ_male_maintenance_01/civ_male_maintenance_01"),
		Idstring("unit"),
		ThisModPath.."xml/6e6969100b52ea22.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_pent/characters/civ_male_guest_penthouse_1/civ_male_guest_penthouse_1"),
		Idstring("unit"),
		ThisModPath.."xml/2f7a2516a99024b0.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_pent/characters/civ_female_guest_penthouse_1/civ_female_guest_penthouse_1"),
		Idstring("unit"),
		ThisModPath.."xml/982300a71d38d8a4.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_pent/characters/civ_female_guest_penthouse_2/civ_female_guest_penthouse_2"),
		Idstring("unit"),
		ThisModPath.."xml/e0b859c662d92866.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_pent/characters/civ_male_receptionist_penthouse/civ_male_receptionist_penthouse"),
		Idstring("unit"),
		ThisModPath.."xml/b73ad39d68704286.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_pent/characters/civ_male_guest_penthouse_2/civ_male_guest_penthouse_2"),
		Idstring("unit"),
		ThisModPath.."xml/8431d4746f068631.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_born/characters/npc_male_mechanic/npc_male_mechanic"),
		Idstring("unit"),
		ThisModPath.."xml/0bc5d8fea12e0c88.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_female_bank_1/civ_female_bank_1"),
		Idstring("unit"),
		ThisModPath.."xml/b72d49236a970630.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_female_bank_manager_1/civ_female_bank_manager_1"),
		Idstring("unit"),
		ThisModPath.."xml/3365ded42485d5b6.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_female_bikini_1/civ_female_bikini_1"),
		Idstring("unit"),
		ThisModPath.."xml/79e39dc9eeab0438.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_female_bikini_2/civ_female_bikini_2"),
		Idstring("unit"),
		ThisModPath.."xml/f3bd9a09c8da6775.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_female_casual_1/civ_female_casual_1"),
		Idstring("unit"),
		ThisModPath.."xml/7dfc5ada7eeca1a9.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_female_casual_2/civ_female_casual_2"),
		Idstring("unit"),
		ThisModPath.."xml/f671c5b16ae24fb3.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_female_casual_3/civ_female_casual_3"),
		Idstring("unit"),
		ThisModPath.."xml/f4e9df0461e7d722.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_female_casual_4/civ_female_casual_4"),
		Idstring("unit"),
		ThisModPath.."xml/e6dc50808da98270.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_female_casual_5/civ_female_casual_5"),
		Idstring("unit"),
		ThisModPath.."xml/73b42c50e0241fd5.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_female_casual_6/civ_female_casual_6"),
		Idstring("unit"),
		ThisModPath.."xml/693a0c3217d8cfd8.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_female_casual_7/civ_female_casual_7"),
		Idstring("unit"),
		ThisModPath.."xml/088fb463584e630d.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_female_casual_8/civ_female_casual_8"),
		Idstring("unit"),
		ThisModPath.."xml/2f41fced983212ea.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_female_casual_9/civ_female_casual_9"),
		Idstring("unit"),
		ThisModPath.."xml/b59553e3808f509f.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_female_casual_10/civ_female_casual_10"),
		Idstring("unit"),
		ThisModPath.."xml/c0bf1513d4c7e6c4.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_female_crackwhore_1/civ_female_crackwhore_1"),
		Idstring("unit"),
		ThisModPath.."xml/16fcba5a46c7f687.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_female_curator_1/civ_female_curator_1"),
		Idstring("unit"),
		ThisModPath.."xml/7d7fcdeea5405168.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_female_curator_2/civ_female_curator_2"),
		Idstring("unit"),
		ThisModPath.."xml/444eab30fefbe378.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_female_hostess_apron_1/civ_female_hostess_apron_1"),
		Idstring("unit"),
		ThisModPath.."xml/82c1367c2a1bcfff.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_female_hostess_jacket_1/civ_female_hostess_jacket_1"),
		Idstring("unit"),
		ThisModPath.."xml/60dc40c3e14c505c.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_female_hostess_shirt_1/civ_female_hostess_shirt_1"),
		Idstring("unit"),
		ThisModPath.."xml/3977a651e6b1a4f3.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_female_party_1/civ_female_party_1"),
		Idstring("unit"),
		ThisModPath.."xml/8e3b8053d96ccaae.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_female_party_2/civ_female_party_2"),
		Idstring("unit"),
		ThisModPath.."xml/874bd00bad7a7602.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_female_party_3/civ_female_party_3"),
		Idstring("unit"),
		ThisModPath.."xml/f580340b1b7f68b2.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_female_party_4/civ_female_party_4"),
		Idstring("unit"),
		ThisModPath.."xml/8bf66caf34240374.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_female_wife_trophy_1/civ_female_wife_trophy_1"),
		Idstring("unit"),
		ThisModPath.."xml/d2cd406e61ea332e.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_female_wife_trophy_2/civ_female_wife_trophy_2"),
		Idstring("unit"),
		ThisModPath.."xml/7f5848259cadb80b.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_bank_1/civ_male_bank_1"),
		Idstring("unit"),
		ThisModPath.."xml/9b7d4a57ef0bc619.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_bank_2/civ_male_bank_2"),
		Idstring("unit"),
		ThisModPath.."xml/c6125145bda6d1d3.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_bank_manager_1/civ_male_bank_manager_1"),
		Idstring("unit"),
		ThisModPath.."xml/893a2aa95b68fac8.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_bank_manager_3/civ_male_bank_manager_3"),
		Idstring("unit"),
		ThisModPath.."xml/75aade30e4b35bd1.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_bank_manager_5/civ_male_bank_manager_5"),
		Idstring("unit"),
		ThisModPath.."xml/b631f2b23c873fe2.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_bartender_1/civ_male_bartender_1"),
		Idstring("unit"),
		ThisModPath.."xml/6c4472dc07afc305.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_bartender_2/civ_male_bartender_2"),
		Idstring("unit"),
		ThisModPath.."xml/10a2a31d93cc4caf.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_business_1/civ_male_business_1"),
		Idstring("unit"),
		ThisModPath.."xml/865aa97229148c58.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_business_2/civ_male_business_2"),
		Idstring("unit"),
		ThisModPath.."xml/fabac6aa6f49c9c3.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_casual_1/civ_male_casual_1"),
		Idstring("unit"),
		ThisModPath.."xml/56274e215bda8dc2.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_casual_2/civ_male_casual_2"),
		Idstring("unit"),
		ThisModPath.."xml/f5bf0941fb89163a.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_casual_3/civ_male_casual_3"),
		Idstring("unit"),
		ThisModPath.."xml/2dcc26b3cce1618e.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_casual_4/civ_male_casual_4"),
		Idstring("unit"),
		ThisModPath.."xml/e7f916e43da4471e.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_casual_5/civ_male_casual_5"),
		Idstring("unit"),
		ThisModPath.."xml/37f340c494e54de0.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_casual_6/civ_male_casual_6"),
		Idstring("unit"),
		ThisModPath.."xml/4ee3cfd2931aff45.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_casual_7/civ_male_casual_7"),
		Idstring("unit"),
		ThisModPath.."xml/968e89568d7f669d.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_casual_8/civ_male_casual_8"),
		Idstring("unit"),
		ThisModPath.."xml/154e1205cb6917e6.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_casual_9/civ_male_casual_9"),
		Idstring("unit"),
		ThisModPath.."xml/65a4d37097cec784.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_casual_12/civ_male_casual_12"),
		Idstring("unit"),
		ThisModPath.."xml/2819d79b24ed0450.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_casual_13/civ_male_casual_13"),
		Idstring("unit"),
		ThisModPath.."xml/d1bb1dd788e51851.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_casual_14/civ_male_casual_14"),
		Idstring("unit"),
		ThisModPath.."xml/d441d40d8dda1145.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_curator_1/civ_male_curator_1"),
		Idstring("unit"),
		ThisModPath.."xml/7c10d2be708d6c1f.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_curator_2/civ_male_curator_2"),
		Idstring("unit"),
		ThisModPath.."xml/d0341cd938db891b.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_curator_3/civ_male_curator_3"),
		Idstring("unit"),
		ThisModPath.."xml/2da24c396911996e.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_dj_1/civ_male_dj_1"),
		Idstring("unit"),
		ThisModPath.."xml/2d92fc58d714d796.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_janitor_1/civ_male_janitor_1"),
		Idstring("unit"),
		ThisModPath.."xml/9d3e6b77701a75c6.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_janitor_2/civ_male_janitor_2"),
		Idstring("unit"),
		ThisModPath.."xml/2c6b69abf266b115.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_janitor_3/civ_male_janitor_3"),
		Idstring("unit"),
		ThisModPath.."xml/d11cedec3c7b5363.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_meth_cook_1/civ_male_meth_cook_1"),
		Idstring("unit"),
		ThisModPath.."xml/1642aea7023af9ee.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_party_1/civ_male_party_1"),
		Idstring("unit"),
		ThisModPath.."xml/f8a42d53750fdb37.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_party_2/civ_male_party_2"),
		Idstring("unit"),
		ThisModPath.."xml/d32946c888b64ed5.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_party_3/civ_male_party_3"),
		Idstring("unit"),
		ThisModPath.."xml/0a36b0e156e3ed42.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_pilot_1/civ_male_pilot_1"),
		Idstring("unit"),
		ThisModPath.."xml/69f8defd593bd56e.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_scientist_1/civ_male_scientist_1"),
		Idstring("unit"),
		ThisModPath.."xml/490549ba47f33eb3.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_miami_store_clerk_1/civ_male_miami_store_clerk_1"),
		Idstring("unit"),
		ThisModPath.."xml/06f1a5d217831681.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_taxman/civ_male_taxman"),
		Idstring("unit"),
		ThisModPath.."xml/7ffb4d20c548a661.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_trucker_1/civ_male_trucker_1"),
		Idstring("unit"),
		ThisModPath.."xml/8082fc9bd7ef9250.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_worker_1/civ_male_worker_1"),
		Idstring("unit"),
		ThisModPath.."xml/e1ce4fecbb3aff4f.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_worker_2/civ_male_worker_2"),
		Idstring("unit"),
		ThisModPath.."xml/5c583b9725cf1ccd.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_worker_3/civ_male_worker_3"),
		Idstring("unit"),
		ThisModPath.."xml/ed38de3c9526f5e9.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_worker_docks_1/civ_male_worker_docks_1"),
		Idstring("unit"),
		ThisModPath.."xml/c33b54baa798417f.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_worker_docks_2/civ_male_worker_docks_2"),
		Idstring("unit"),
		ThisModPath.."xml/a52aab465cbba1d1.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_worker_docks_3/civ_male_worker_docks_3"),
		Idstring("unit"),
		ThisModPath.."xml/b7806766933993c8.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_dog_abuser_1/civ_male_dog_abuser_1"),
		Idstring("unit"),
		ThisModPath.."xml/3dd2249a6c052d10.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/payday2/characters/civ_male_dog_abuser_2/civ_male_dog_abuser_2"),
		Idstring("unit"),
		ThisModPath.."xml/c97f507107bf0fdd.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_auc/characters/civ_male_auc_brother_1/civ_male_auc_brother_1"),
		Idstring("unit"),
		ThisModPath.."xml/b8d06661e57a50cc.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_auc/characters/civ_male_auc_brother_2/civ_male_auc_brother_2"),
		Idstring("unit"),
		ThisModPath.."xml/e9e482e477c0ccf7.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_auc/characters/civ_male_auc_worker_1/civ_male_auc_worker_1"),
		Idstring("unit"),
		ThisModPath.."xml/faf18710d05750d0.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_auc/characters/civ_male_auc_worker_2/civ_male_auc_worker_2"),
		Idstring("unit"),
		ThisModPath.."xml/240a04f1f7ed841d.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_auc/characters/civ_male_auc_worker_3/civ_male_auc_worker_3"),
		Idstring("unit"),
		ThisModPath.."xml/dca59c99e526f4b6.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_auc/characters/civ_female_auc_worker_1/civ_female_auc_worker_1"),
		Idstring("unit"),
		ThisModPath.."xml/71eebb6610b57459.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_auc/characters/civ_female_auc_worker_2/civ_female_auc_worker_2"),
		Idstring("unit"),
		ThisModPath.."xml/5954b08542f9c3e7.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_auc/characters/civ_female_auc_worker_3/civ_female_auc_worker_3"),
		Idstring("unit"),
		ThisModPath.."xml/9135a59fe0454e61.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_auc/characters/civ_female_auc_lead_curator_1/civ_female_auc_lead_curator_1"),
		Idstring("unit"),
		ThisModPath.."xml/bbf62b4aa7fd0fae.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_casino/characters/civ_male_casino_1/civ_male_casino_1"),
		Idstring("unit"),
		ThisModPath.."xml/71a28ac2d23a9d78.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_casino/characters/civ_male_casino_2/civ_male_casino_2"),
		Idstring("unit"),
		ThisModPath.."xml/9c8bb6c123b06470.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_casino/characters/civ_male_casino_3/civ_male_casino_3"),
		Idstring("unit"),
		ThisModPath.."xml/54c95297d5789a56.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_casino/characters/civ_male_casino_4/civ_male_casino_4"),
		Idstring("unit"),
		ThisModPath.."xml/bc0e539fbf275dc1.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_casino/characters/civ_male_business_casino_1/civ_male_business_casino_1"),
		Idstring("unit"),
		ThisModPath.."xml/734ccb8105ddfc40.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_casino/characters/civ_male_business_casino_2/civ_male_business_casino_2"),
		Idstring("unit"),
		ThisModPath.."xml/7757a7ebadeb8891.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_casino/characters/civ_male_impersonator/civ_male_impersonator"),
		Idstring("unit"),
		ThisModPath.."xml/4d1f89960be8fc5d.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_casino/characters/civ_female_casino_1/civ_female_casino_1"),
		Idstring("unit"),
		ThisModPath.."xml/c2ea88083fddd57d.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_casino/characters/civ_female_casino_2/civ_female_casino_2"),
		Idstring("unit"),
		ThisModPath.."xml/6d5118d4f2186871.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_casino/characters/civ_female_casino_3/civ_female_casino_3"),
		Idstring("unit"),
		ThisModPath.."xml/e3acc85aaccbec46.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_casino/characters/civ_male_casino_pitboss/civ_male_casino_pitboss"),
		Idstring("unit"),
		ThisModPath.."xml/d64389329d673d66.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_pex/characters/civ_male_janitor_pex_01/civ_male_janitor_pex_01"),
		Idstring("unit"),
		ThisModPath.."xml/4909219f151501a3.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_pex/characters/civ_male_janitor_pex_02/civ_male_janitor_pex_02"),
		Idstring("unit"),
		ThisModPath.."xml/146b93ac2145f69c.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_pex/characters/npc_male_vladbroinlaw_pex/npc_male_vladbroinlaw_pex"),
		Idstring("unit"),
		ThisModPath.."xml/33de0bc42ee910da.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_pex/characters/npc_male_vladbroinlaw_pex_bloody/npc_male_vladbroinlaw_pex_bloody"),
		Idstring("unit"),
		ThisModPath.."xml/ac36647a12776746.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_pex/characters/npc_male_vladbroinlaw_cop_pex/npc_male_vladbroinlaw_cop_pex"),
		Idstring("unit"),
		ThisModPath.."xml/06647e716233e932.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_cage/characters/civ_female_bank_2/civ_female_bank_2"),
		Idstring("unit"),
		ThisModPath.."xml/c05fd115516469d6.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_bph/characters/civ_male_bain/civ_male_bain"),
		Idstring("unit"),
		ThisModPath.."xml/72c44d701279a7ad.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_skirmish/characters/civ_male_bank_manager_hostage/civ_male_bank_manager_hostage"),
		Idstring("unit"),
		ThisModPath.."xml/4c7edf6a7fb52dbb.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_skirmish/characters/civ_female_museum_curator_hostage/civ_female_museum_curator_hostage"),
		Idstring("unit"),
		ThisModPath.."xml/dc8cdcef536a2002.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_skirmish/characters/civ_female_drug_lord_hostage/civ_female_drug_lord_hostage"),
		Idstring("unit"),
		ThisModPath.."xml/272888dfb4ceeab9.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_skirmish/characters/civ_male_prisoner_hostage/civ_male_prisoner_hostage"),
		Idstring("unit"),
		ThisModPath.."xml/29a47a619765c157.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_ranc/characters/civ_male_ranchmanager_1/civ_male_ranchmanager_1"),
		Idstring("unit"),
		ThisModPath.."xml/7fbee5470f713f41.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_ranc/characters/civ_male_weaponworker_1/civ_male_weaponworker_1"),
		Idstring("unit"),
		ThisModPath.."xml/ba5ec25711b341d3.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_ranc/characters/civ_male_weaponworker_2/civ_male_weaponworker_2"),
		Idstring("unit"),
		ThisModPath.."xml/e2d8a7bb1da9910d.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_ranc/characters/civ_male_ranch_worker_1/civ_male_ranch_worker_1"),
		Idstring("unit"),
		ThisModPath.."xml/7b7d8ac3aac45369.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_ranc/characters/civ_male_ranch_worker_2/civ_male_ranch_worker_2"),
		Idstring("unit"),
		ThisModPath.."xml/dfb6a6e2ddadc3d2.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_ranc/characters/civ_male_ranch_worker_3/civ_male_ranch_worker_3"),
		Idstring("unit"),
		ThisModPath.."xml/b1b7c7b9034cd529.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_moon/characters/civ_male_pilot_2/civ_male_pilot_2"),
		Idstring("unit"),
		ThisModPath.."xml/0c08e4de7daa778c.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_sand/characters/civ_male_vlad/civ_male_vlad"),
		Idstring("unit"),
		ThisModPath.."xml/09fc4648b4f220bc.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_sand/characters/civ_male_dockworker_01/civ_male_dockworker_01"),
		Idstring("unit"),
		ThisModPath.."xml/f05ba7e62226e93c.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_sand/characters/civ_male_dockworker_02/civ_male_dockworker_02"),
		Idstring("unit"),
		ThisModPath.."xml/ae332165c2f85b77.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_sand/characters/civ_male_dockworker_03/civ_male_dockworker_03"),
		Idstring("unit"),
		ThisModPath.."xml/8052ef8b097f3ded.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_slu/characters/npc_vlad/npc_vlad"),
		Idstring("unit"),
		ThisModPath.."xml/ea73374639b8b416.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_slu/characters/npc_sophia/npc_sophia"),
		Idstring("unit"),
		ThisModPath.."xml/8e74a093d058fefb.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_lxy/characters/civ_female_guest_gala_1/civ_female_guest_gala_1"),
		Idstring("unit"),
		ThisModPath.."xml/b731dc81bbe9a602.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_lxy/characters/civ_female_guest_gala_2/civ_female_guest_gala_2"),
		Idstring("unit"),
		ThisModPath.."xml/b4b605e5886096de.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_lxy/characters/civ_male_guest_gala_1/civ_male_guest_gala_1"),
		Idstring("unit"),
		ThisModPath.."xml/13e428eb28bc0e73.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_lxy/characters/civ_male_guest_gala_2/civ_male_guest_gala_2"),
		Idstring("unit"),
		ThisModPath.."xml/44a1a0e887645fa5.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_lxy/characters/civ_male_camera_crew_1/civ_male_camera_crew_1"),
		Idstring("unit"),
		ThisModPath.."xml/0856cc3661560c7e.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_peta/characters/civ_male_boris/civ_male_boris"),
		Idstring("unit"),
		ThisModPath.."xml/c7c310d69ce386e0.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_chca/characters/civ_male_boss_2/civ_male_boss_2"),
		Idstring("unit"),
		ThisModPath.."xml/a34dfeddca16e564.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_chca/characters/civ_male_bathhouse_1/civ_male_bathhouse_1"),
		Idstring("unit"),
		ThisModPath.."xml/02dd877173b59dbd.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_chca/characters/civ_male_bathhouse_2/civ_male_bathhouse_2"),
		Idstring("unit"),
		ThisModPath.."xml/45cfbd3c5245de1d.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_chca/characters/civ_male_bathhouse_3/civ_male_bathhouse_3"),
		Idstring("unit"),
		ThisModPath.."xml/3adaab6ffaf3e8b4.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_chca/characters/civ_female_bathhouse_1/civ_female_bathhouse_1"),
		Idstring("unit"),
		ThisModPath.."xml/6f2da2805089b540.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_chca/characters/civ_female_bathhouse_2/civ_female_bathhouse_2"),
		Idstring("unit"),
		ThisModPath.."xml/7658ff4b620bf115.unit"
	)
	BLT.AssetManager:CreateEntry(
		Idstring("units/pd2_dlc_run/characters/npc_matt/npc_matt"),
		Idstring("unit"),
		ThisModPath.."xml/78964c9af5f85f95.unit"
	)
end)