HuskCopInventory.JOKERMASK_Can_I_Have_Mask = CopInventory.JOKERMASK_Can_I_Have_Mask
HuskCopInventory.JOKERMASK_apply_mask = CopInventory.JOKERMASK_apply_mask
HuskCopInventory.JOKERMASK_clbk_mask_unit_loaded = CopInventory.JOKERMASK_clbk_mask_unit_loaded
HuskCopInventory.JOKERMASK_unload_mask = CopInventory.JOKERMASK_unload_mask
HuskCopInventory.JOKERMASK_reset_JOKER_mask_visibility = CopInventory.JOKERMASK_reset_JOKER_mask_visibility
HuskCopInventory.JOKERMASK_pre_destroy = CopInventory.JOKERMASK_pre_destroy
HuskCopInventory.JOKERMASK_set_JOKER_mask_visibility = CopInventory.JOKERMASK_set_JOKER_mask_visibility